version: '3.5'
services:
  nginx:
    image: nginx:alpine
    container_name: random1-nginx
    working_dir: /var/www/random1
    volumes:
      - ./:/var/www/random1
      - ./docker.dev/nginx/random1.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - postgres
    depends_on:
      - php
      - postgres
    ports:
      - 81:80
  php:
    container_name: random1-php
    build:
      context: docker.dev/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/random1
      - ./docker.dev/php/php.ini:/usr/local/etc/php/conf.d/z-php.ini
    working_dir: /var/www/random1
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 9001:9000
  postgres:
    container_name: random1-postgres
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./docker.dev/volumes/postgres:/data/postgres
    ports:
      - 5433:5432
